name: travio_admin_
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  awesome_bottom_bar: ^1.2.4
  barcode_widget: ^2.0.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.1.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  file_picker: ^8.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_countries: ^1.0.2
  flutter_svg: ^2.0.10+1
  multiple_images_picker: ^1.0.1
  provider: ^6.1.2
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/

# To add assets to your application, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
